public struct Game {
	let randomSeed: Int64
	let tickCount: Int
	let worldWidth: Double
	let worldHeight: Double
	let fogOfWarEnabled: Bool
	let victoryScore: Int
	let facilityCaptureScore: Int
	let vehicleEliminationScore: Int
	let actionDetectionInterval: Int
	let baseActionCount: Int
	let additionalActionCountPerControlCenter: Int
	let maxUnitGroup: Int
	let terrainWeatherMapColumnCount: Int
	let terrainWeatherMapRowCount: Int
	let plainTerrainVisionFactor: Double
	let plainTerrainStealthFactor: Double
	let plainTerrainSpeedFactor: Double
	let swampTerrainVisionFactor: Double
	let swampTerrainStealthFactor: Double
	let swampTerrainSpeedFactor: Double
	let forestTerrainVisionFactor: Double
	let forestTerrainStealthFactor: Double
	let forestTerrainSpeedFactor: Double
	let clearWeatherVisionFactor: Double
	let clearWeatherStealthFactor: Double
	let clearWeatherSpeedFactor: Double
	let cloudWeatherVisionFactor: Double
	let cloudWeatherStealthFactor: Double
	let cloudWeatherSpeedFactor: Double
	let rainWeatherVisionFactor: Double
	let rainWeatherStealthFactor: Double
	let rainWeatherSpeedFactor: Double
	let vehicleRadius: Double
	let tankDurability: Int
	let tankSpeed: Double
	let tankVisionRange: Double
	let tankGroundAttackRange: Double
	let tankAerialAttackRange: Double
	let tankGroundDamage: Int
	let tankAerialDamage: Int
	let tankGroundDefence: Int
	let tankAerialDefence: Int
	let tankAttackCooldownTicks: Int
	let tankProductionCost: Int
	let ifvDurability: Int
	let ifvSpeed: Double
	let ifvVisionRange: Double
	let ifvGroundAttackRange: Double
	let ifvAerialAttackRange: Double
	let ifvGroundDamage: Int
	let ifvAerialDamage: Int
	let ifvGroundDefence: Int
	let ifvAerialDefence: Int
	let ifvAttackCooldownTicks: Int
	let ifvProductionCost: Int
	let arrvDurability: Int
	let arrvSpeed: Double
	let arrvVisionRange: Double
	let arrvGroundDefence: Int
	let arrvAerialDefence: Int
	let arrvProductionCost: Int
	let arrvRepairRange: Double
	let arrvRepairSpeed: Double
	let helicopterDurability: Int
	let helicopterSpeed: Double
	let helicopterVisionRange: Double
	let helicopterGroundAttackRange: Double
	let helicopterAerialAttackRange: Double
	let helicopterGroundDamage: Int
	let helicopterAerialDamage: Int
	let helicopterGroundDefence: Int
	let helicopterAerialDefence: Int
	let helicopterAttackCooldownTicks: Int
	let helicopterProductionCost: Int
	let fighterDurability: Int
	let fighterSpeed: Double
	let fighterVisionRange: Double
	let fighterGroundAttackRange: Double
	let fighterAerialAttackRange: Double
	let fighterGroundDamage: Int
	let fighterAerialDamage: Int
	let fighterGroundDefence: Int
	let fighterAerialDefence: Int
	let fighterAttackCooldownTicks: Int
	let fighterProductionCost: Int
	let maxFacilityCapturePoints: Double
	let facilityCapturePointsPerVehiclePerTick: Double
	let facilityWidth: Double
	let facilityHeight: Double
}
